### ISSUE TITLE
Anwendungsfallbeschreibungen nicht vergessen!!!

### ISSUE THREAD

**Issue by mageroya** [sweIif3bgows1516/TG1-4#2]
Hey Leute, bis morgen um 11:55 muss der fuck abgegeben werden. Und einer muss noch mergen und PDFen!

**Comment by Benni4** [comment]
Ich hab in solutions und in TG1-4 meine Zutat hinzufügen commited

**Comment by Benni4** [comment]
Kannst du das nochmal als normales pdf committen? Kann xlsx nicht öffnen

**Comment by Benni4** [comment]
Dann mach ich alles in ein PDF oder ZIP und lad es bei moodle hoch

**Comment by mageroya** [comment]
ich fügs zusammen, passt

**Comment by Benni4** [comment]
Ah super, merci dir.

**Comment by mageroya** [comment]
done: db3078dfdf6b66fa8fbdef92972c7da530e0e3f5
