### ISSUE TITLE
UMLfick zu unsrem projekt

### ISSUE THREAD

**Issue by mageroya** [sweIif3bgows1516/TG1-4#3]
Da steht in der Abgabe was, was wir ganz vergessen ham: es muss ja noch was gemalt werden -_-

> Abgabe (2 Files) im Team:
> 
>     Executable (.apk-File (für Android) oder .jar-File/.html File (für Webanwendung))
>     in einem PDF Dokument
>
>        - Sprint-Ziel
>        - Sprint Backlog mit UML Diagramm (z.B. Klassendiagramm und/oder Sequenzdiagramm) für jede User Story

**Comment by MarkusKral** [comment]
hab mal n paar Diagramme gezeichnet, sind halt ziemlich simpel gehalten.
Bitte mal drueberschauen ob OK.

LG

**Comment by mageroya** [comment]
danke! hab grad noch die abgabe a bisl bearbeitet, jetzt solltes passen.
6b885ca0e72a98520e531be53ba902b95a62ebcb
closed.

**Comment by MarkusKral** [comment]
was noch gefehlt hat: sprint-ziel ins pdf mergen.
Done in Abgabe-fin.pdf
commit 23e880ce0e6b4807e172bb1d5eeaf0747cb0aabd

**Comment by mageroya** [comment]
neee, jetzt ham wir zwei sprint ziele! ich hab abends noch eins gsbaut, und dann festgsstellt, da steht schon eins überm backlog!!

**Comment by MarkusKral** [comment]
Naja, jetz hat sies in meiner Abgabe halt doppelt,  scheiß drauf. 

Komm mal wieder n paar min später, in pasing hats stellwerkstörungen ^^
