### ISSUE TITLE
URL zu Ihrer Demoversion

### ISSUE THREAD

**Issue by gsocher** [sweIif3bgows1516/TG1-4#5]
Hallo zusammen, 

heute Nachmittag führe ich die aktuellen Protypen beim SCE vor. Können Sie mir bitte die URL Ihres Servers nennen? Es wäre prima, wenn ich diese URL für die Demo nehmen darf.

Danke!
Gudrun Socher

**Comment by mageroya** [comment]
ich habs in moodle als abgabekommentar reingeschrieben :) 
softeng.romanbendt.com
sie können das projekt gerne zur demo benutzen.

**Comment by gsocher** [comment]
super. Danke!!
___________________________________________________________
*Prof. Dr. Gudrun Socher*
Human Computer Interaction
Fakultät für Informatik & Mathematik - Computer Science & Mathematics
Hochschule München - Munich University of Applied Sciences
R 4.029 | Lothstrasse 64 | 80335 München | Germany
+49 89 1265 3743 | gudrun.socher@hm.edu <mailto:gudrun.socher@hm.edu> |
cs.hm.edu/~socher <http://cs.hm.edu/%7Esocher>
___________________________________________________________
Am 01.12.2015 um 11:53 schrieb mageroya:
