### ISSUE TITLE
chaos bei den bussen

### ISSUE THREAD

**Issue by mageroya** [sweIif3bgows1516/TG1-4#6]
kann ned garantieren dass ich rechtzeitig komm

**Comment by MarkusKral** [comment]
Alles gut, müssen ja eh nur die Abgabe machen, haben also keinen Stress 

On December 3, 2015 9:26:48 AM GMT+01:00, mageroya <notifications@github.com> wrote:
>kann ned garantieren dass ich rechtzeitig komm
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sweIif3bgows1516/TG1-4/issues/6

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
