### ISSUE TITLE
Treffen Dienstag?

### ISSUE THREAD

**Issue by MarkusKral** [sweIif3bgows1516/TG1-4#7]
Servus,

wann hocken wir uns nochmal zusammen um die Abgabe fertig zu machen?

LG
Markus

**Comment by Benni4** [comment]
Ja heute ab drei dachte ich? Ich komm aber wahrscheinlich erst um fünf. Vielleicht könntet ihr mir dann schreiben wo ihr seid. 01721620978

**Comment by MarkusKral** [comment]
Alles klar, hatte nur den Termin vergessen, dann treffen wir zwei anderen uns um 3 beim der Kantine, dir schreib ich dann.

**Comment by mageroya** [comment]
wir hatten 15:30 gesagt, ich hock grad no im praktilkum ^^

**Comment by MarkusKral** [comment]
alles klar,  ich hock in 1006
